// n8nIntegration.ts - helper to forward prompts to an n8n workflow
import fetch from 'node-fetch';
import dotenv from 'dotenv';

dotenv.config();

/**
 * Sends a prompt to an n8n HTTP webhook and returns the response text.
 * The webhook URL must be configured in the environment variable N8N_WEBHOOK_URL.
 *
 * @param from   Identifier of the user (phone number or chat ID)
 * @param prompt The message text that should be processed by the n8n workflow
 * @returns The reply generated by n8n, or null on error
 */
export async function sendToN8N(from: string, prompt: string): Promise<string | null> {
  const webhookUrl = process.env.N8N_WEBHOOK_URL;
  if (!webhookUrl) {
    console.warn('[n8n] N8N_WEBHOOK_URL not set – skipping n8n integration');
    return null;
  }

  try {
    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ from, prompt }),
    });

    if (!response.ok) {
      const err = await response.text();
      console.error('[n8n] Bad response', response.status, err);
      return null;
    }
    const data = await response.json();
    // Expect the workflow to return { reply: string }
    return data.reply ?? null;
  } catch (e: any) {
    console.error('[n8n] Network error', e.message);
    return null;
  }
}
